nnoremap <space> <Cmd>call VSCodeNotify('workbench.debug.action.toggleRepl')<CR>
nnoremap <space> <Cmd>call VSCodeNotify('workbench.view.explorer')<CR>
nnoremap <space> <Cmd>call VSCodeNotify('workbench.view.scm')<CR>
nnoremap <space> <Cmd>call VSCodeNotify('notifications.toggleList')<CR>
nnoremap <space> <Cmd>call VSCodeNotify('workbench.action.output.toggleOutput')<CR>
nnoremap <space> <Cmd>call VSCodeNotify('workbench.actions.view.problems')<CR>
nnoremap <space> <Cmd>call VSCodeNotify('workbench.view.remote')<CR>
nnoremap <space> <Cmd>call VSCodeNotify('workbench.view.search')<CR>
nnoremap <space> <Cmd>call VSCodeNotify('workbench.view.extension.test')<CR>
nnoremap <space> <Cmd>call VSCodeNotify('workbench.view.extensions')<CR>