nnoremap <space>Sd <Cmd>call VSCodeNotify('workbench.debug.action.toggleRepl')<CR>
nnoremap <space>Se <Cmd>call VSCodeNotify('workbench.view.explorer')<CR>
nnoremap <space>Sg <Cmd>call VSCodeNotify('workbench.view.scm')<CR>
nnoremap <space>Sn <Cmd>call VSCodeNotify('notifications.toggleList')<CR>
nnoremap <space>So <Cmd>call VSCodeNotify('workbench.action.output.toggleOutput')<CR>
nnoremap <space>Sp <Cmd>call VSCodeNotify('workbench.actions.view.problems')<CR>
nnoremap <space>Sr <Cmd>call VSCodeNotify('workbench.view.remote')<CR>
nnoremap <space>Ss <Cmd>call VSCodeNotify('workbench.view.search')<CR>
nnoremap <space>St <Cmd>call VSCodeNotify('workbench.view.extension.test')<CR>
nnoremap <space>Sx <Cmd>call VSCodeNotify('workbench.view.extensions')<CR>