nnoremap <space>Tb <Cmd>call VSCodeNotify('workbench.action.toggleSidebarVisibility')<CR>
nnoremap <space>Tc <Cmd>call VSCodeNotify('workbench.action.toggleCenteredLayout')<CR>
nnoremap <space>Ti <Cmd>call VSCodeNotify('workbench.action.selectIconTheme')<CR>
nnoremap <space>Tj <Cmd>call VSCodeNotify('workbench.action.togglePanel')<CR>
nnoremap <space>Tm <Cmd>call VSCodeNotify('workbench.action.toggleMaximizedPanel')<CR>
nnoremap <space>Ts <Cmd>call VSCodeNotify('workbench.action.selectTheme')<CR>
nnoremap <space>Tt <Cmd>call VSCodeNotify('workbench.action.toggleActivityBarVisibility')<CR>
nnoremap <space>Tz <Cmd>call VSCodeNotify('workbench.action.toggleZenMode')<CR>
nnoremap <space>TF <Cmd>call VSCodeNotify('workbench.action.toggleFullScreen')<CR>
nnoremap <space>TT <Cmd>call VSCodeNotify('workbench.action.toggleTabsVisibility')<CR>