nnoremap <space>xmb <Cmd>call VSCodeNotify('merge-conflict.accept.both')<CR>
nnoremap <space>xmc <Cmd>call VSCodeNotify('merge-conflict.accept.current')<CR>
nnoremap <space>xmi <Cmd>call VSCodeNotify('merge-conflict.accept.incoming')<CR>
nnoremap <space>xmk <Cmd>call VSCodeNotify('merge-conflict.compare')<CR>
nnoremap <space>xmn <Cmd>call VSCodeNotify('merge-conflict.next')<CR>
nnoremap <space>xms <Cmd>call VSCodeNotify('merge-conflict.accept.selection')<CR>
nnoremap <space>xmB <Cmd>call VSCodeNotify('merge-conflict.accept.all-both')<CR>
nnoremap <space>xmC <Cmd>call VSCodeNotify('merge-conflict.accept.all-current')<CR>
nnoremap <space>xmI <Cmd>call VSCodeNotify('merge-conflict.accept.all-incoming')<CR>
nnoremap <space>xmN <Cmd>call VSCodeNotify('merge-conflict.previous')<CR>