nnoremap <space>fyc <Cmd>call VSCodeNotify('vspacecode.copyPathWithLineColumn')<CR>
nnoremap <space>fyd <Cmd>call VSCodeNotify('vspacecode.copyDirectoryPath')<CR>
nnoremap <space>fyl <Cmd>call VSCodeNotify('vspacecode.copyPathWithLine')<CR>
nnoremap <space>fyn <Cmd>call VSCodeNotify('vspacecode.copyFilename')<CR>
nnoremap <space>fyy <Cmd>call VSCodeNotify('vspacecode.copyPath')<CR>
nnoremap <space>fyC <Cmd>call VSCodeNotify('vspacecode.copyRelativePathWithLineColumn')<CR>
nnoremap <space>fyD <Cmd>call VSCodeNotify('vspacecode.copyRelativeDirectoryPath')<CR>
nnoremap <space>fyL <Cmd>call VSCodeNotify('vspacecode.copyRelativePathWithLine')<CR>
nnoremap <space>fyN <Cmd>call VSCodeNotify('vspacecode.copyFilenameBase')<CR>
nnoremap <space>fyY <Cmd>call VSCodeNotify('vspacecode.copyRelativePath')<CR>