nnoremap <space>z.a <Cmd>call VSCodeNotify('editor.toggleFold')<CR>
nnoremap <space>z.b <Cmd>call VSCodeNotify('editor.foldAllBlockComments')<CR>
nnoremap <space>z.c <Cmd>call VSCodeNotify('editor.fold')<CR>
nnoremap <space>z.g <Cmd>call VSCodeNotify('editor.foldAllMarkerRegions')<CR>
nnoremap <space>z.m <Cmd>call VSCodeNotify('editor.foldAll')<CR>
nnoremap <space>z.o <Cmd>call VSCodeNotify('editor.unfold')<CR>
nnoremap <space>z.r <Cmd>call VSCodeNotify('editor.unfoldAll')<CR>
nnoremap <space>z.G <Cmd>call VSCodeNotify('editor.unfoldAllMarkerRegions')<CR>
nnoremap <space>z.O <Cmd>call VSCodeNotify('editor.unfoldRecursively')<CR>